name: Projection Update Pre-Deployment

# Controls when the action will run. Triggers the workflow on PR 
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check"
  csv_checks:
    # The type of docker container that the job will run on
    runs-on: ubuntu-latest

    # Check if PR is coming from projection_updates branch
    if: contains(github.head_ref, 'projection_updates') == true
    steps:
    - name: Checkout projection_updates 
      uses: actions/checkout@v2
      with: 
        ref: projection_updates 

    - name: Copy staged CSVs to /tmp
      run: cp ./data/predicted/Global.csv /tmp/Global-staged.csv

    - name: Checkout master
      uses: actions/checkout@v2
      with: 
        ref: master

    - name: Copy master CSVs to /tmp
      run: cp ./data/predicted/Global.csv /tmp/Global-master.csv

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip3 install pandas

    - name: Compare CSVs
      run: |
        echo Comparing CSVs...
        python3 ./.github/workflows/deployment-scripts/compare_dfs.py /tmp/Global-staged.csv /tmp/Global-master.csv

    - name: Auto-Merge PR 
      uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#TODO: Tell predictions team to label their PRs, so that only those labels get merged for extra safety
        MERGE_LABELS: ""
