name: Projection Update Pre-Deployment Checks

# Controls when the action will run. Triggers the workflow on PR 
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check"
  check:
    # The type of docker container that the job will run on
    runs-on: ubuntu-latest

    # Check if PR is coming from projection_updates branch
    if: contains(github.head_ref, 'projection_updates') == true
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with: 
        ref: master

    - name: Copy CSVs to /tmp
      run: cp ./data/predicted/Global.csv /tmp/Global-master.csv

    - name: Checkout projection_updates 
      uses: actions/checkout@v2
      with: 
        ref: projection_updates 

    - name: Copy CSVs to /tmp
      run: cp ./data/predicted/Global.csv /tmp/Global-staged.csv

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip3 install pandas

    - name: Compare CSVs
      run: |
        echo Comparing CSVs...
        python3 ./CI/compare_dfs.py /tmp/Global-staged.csv /tmp/Global-master.csv
